apiVersion: v1
kind: Namespace
metadata:
  name: fastapi-todo-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub
  namespace: fastapi-todo-dev
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJodW5ndHJhbjEyNjYiLCJwYXNzd29yZCI6ImRja3JfcGF0X0EzU2FLMTNtQk5OazlPQkJLUG5yU3BRUHlxQSIsImVtYWlsIjoiaHVuZ2hlb2RlcHRyYWlzbzI1QGdtYWlsLmNvbSIsImF1dGgiOiJhSFZ1WjNSeVlXNHhNalkyT21SamEzSmZjR0YwWDBFelUyRkxNVE50UWs1T2F6bFBRa0pMVUc1eVUzQlJVSGx4UVE9PSJ9fX0=
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  namespace: fastapi-todo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      imagePullSecrets:
        - name: dockerhub
      containers:
        - name: backend-api
          image: hungtran1266/fast-api:bd2761dd82b08a76b780ded3c5b2fd22de24f13e
          resources:
            requests:
              cpu: "256m"
              memory: "512Mi"
            limits:
              memory: "1024Mi"
              cpu: "512m"
          ports:
            - containerPort: 8000
              name: backend-api
